version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fitness-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db
    ports:
      - "5173:5173"
      
  web:
    image: nginx:alpine
    container_name: fitness-nginx
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: fitness-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fitness_app
      MYSQL_USER: sail
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
